### ISSUE TITLE
Make sure linkchecker only has read permissions

### ISSUE THREAD

**Issue by busykoala** [4teamwork/ftw.linkchecker#27]
It is important that the linkchecker only has read permissions. Otherwise he might delete content.

**Comment by maethu** [comment]
Mit transaction.doom() kann sichergestellt werden, dass keine Veränderungen an der DB commited werden.

**Comment by maethu** [comment]
Since the script run it's own instance, All possible changes are not committed anyway.
So this issues has been resolved by design of the software 👍
