### ISSUE TITLE
Relations having whitespace can not be resolved

### ISSUE THREAD

**Issue by busykoala** [4teamwork/ftw.linkchecker#49]
There is a case where whitespace can damage resolving relations (either whitespace or %20). I'm not sure about that yet.

Since on clicking these relations they can be resolved, we should think about also changing them to valid relations even though they are not nice to have on websites.

**Comment by busykoala** [comment]
@maethu, what do you think? Should we tell the Webmaster about these relations, or just ignore them as valid ones?

**Comment by maethu** [comment]
I don't know how they are produced... Do you have any example?

BTW: `%20` is a whitespace but URLEncoded

**Comment by busykoala** [comment]
For now we'll ignore these.
