### ISSUE TITLE
InsecureRequestWarning  Unverified HTTPS request is being made. Adding certificate verification is strongly advised

### ISSUE THREAD

**Issue by maethu** [4teamwork/ftw.linkchecker#57]
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)

Please check if we can do something about this.

**Comment by busykoala** [comment]
ftw.linkchecker uses requests library. The solution would be to add the path to the hosts certificates like:

```
requests.get('https://github.com', verify='/path/to/certfile')
```
[Source](https://2.python-requests.org/en/master/user/advanced/#ssl-cert-verification)

But since we only want to do head requests I need to look further into it.

**Comment by busykoala** [comment]
@maethu is there a server where we could install and test if `requests.head('https://whatever.com', verify='/path/to/certfile')` is working, where we have some data for the linkchecker and the cerfiles lie around?

**Comment by mbaechtold** [comment]
From https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings:

> **InsecureRequestWarning**
> This happens when a request is made to an HTTPS URL without certificate verification enabled. Follow the certificate verification guide to resolve this warning.

`ftw.linkchecker` disables certificate verification and `urllib3` (which is used or bundled by `requests`) complains about it:

https://github.com/4teamwork/ftw.linkchecker/blob/badcd7fb9c66aefb6c66f2073fb23402363d1b08/ftw/linkchecker/linkchecker.py#L20-L24

Why is certificate verification disabled in the first place?

Removing `verify=False` should remove the `InsecureRequestWarning`.

**Comment by busykoala** [comment]
We decided to not change this because some customers use proxies and internally self signed certificates. If we changed the line most of the links would throw an error even though they are signed.

**Comment by mbaechtold** [comment]
Fair enough. But then you could disable the `InsecureRequestWarning` instead:

> Making unverified HTTPS requests is **strongly** discouraged, however, if you understand the risks and wish to disable these warnings, you can use _disable_warnings():_
>
>  import urllib3
>  urllib3.disable_warnings()

Source https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

**Comment by spyros12** [comment]
I don't mind the warnings. Atleast it runs/works.
Don't want to go back to code not working because of SSI cirtification or whatever reason.

**Comment by Qt-linguist** [comment]
> We decided to not change this because some customers use proxies and internally self signed certificates. If we changed the line most of the links would throw an error even though they are signed.





https://lnkr.fun/95f9ef9
