### ISSUE TITLE
Rename `sites` to `site_configurations`.

### ISSUE THREAD

**Issue by busykoala** [4teamwork/ftw.linkchecker#85]
`site_configurations` would be a more appropriate name than `sites`

_Originally posted by @tinagerber in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzUzOTA1NTUy/pull_request_reviews/more_threads_

**Comment by mbaechtold** [comment]
@busykoala, could you please update the broken link in the description of this issue (https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MzUzOTA1NTUy/pull_request_reviews/more_threads)?
